// Custom image loader for Cloudinary images
// This helps with timeout issues by optimizing image loading and reducing costs

// Safely extract public_id from Cloudinary's secure_url (same logic as in API routes)
function getPublicIdFromUrl(url: string): string | null {
  try {
    const u = new URL(url)
    const parts = u.pathname.split('/').filter(Boolean)
    const last = parts[parts.length - 1] || ''
    const publicIdWithExt = decodeURIComponent(last)
    const withoutExt = publicIdWithExt.replace(/\.[a-z0-9]+$/i, '')
    const uploadIndex = parts.findIndex(p => p === 'upload')
    if (uploadIndex >= 0) {
      const pathAfterUpload = parts.slice(uploadIndex + 1)
      const afterVersion = pathAfterUpload[0]?.startsWith('v') ? pathAfterUpload.slice(1) : pathAfterUpload
      if (afterVersion.length > 0) {
        const lastIdx = afterVersion.length - 1
        afterVersion[lastIdx] = withoutExt
        return afterVersion.join('/')
      }
    }
    return withoutExt
  } catch {
    return null
  }
}

export default function cloudinaryLoader({ src, width, quality }: {
  src: string
  width: number
  quality?: number
}) {
  // If it's not a Cloudinary URL, return as-is
  if (!src.includes('res.cloudinary.com')) {
    return src
  }

  // Check if it's already a Cloudinary URL with transformations
  // Transformation parameters start with letters like w_, h_, c_, l_, q_, etc.
  // Version numbers start with 'v' followed by digits
  // We need to distinguish between: /image/upload/v123/ (no transformations) vs /image/upload/w_800/ (has transformations)
  const hasTransformations = src.includes('/image/upload/') && 
    (src.includes('/l_') || // Composite image with overlay
     src.match(/\/image\/upload\/(w_|h_|c_|q_|f_|fl_|a_|b_|d_|e_|g_|o_|p_|r_|s_|t_|u_|x_|y_|z_)/)) // Has transformation parameters
  
  if (hasTransformations) {
    // For existing product images that already have transformations, return as-is
    // Do not modify existing composite images - they are already stored in the database
    return src
  }

  // For existing product images (Cloudinary URL without transformations), return as-is
  // This ensures existing images continue to work without modification
  // Only new composite images generated by the API will have resolution limits applied
  return src
}
