// Custom image loader for Cloudinary images
// This helps with timeout issues by optimizing image loading and reducing costs

export default function cloudinaryLoader({ src, width: _width, quality: _quality }: {
  src: string
  width: number
  quality?: number
}) {
  // If it's not a Cloudinary URL, return as-is
  if (!src.includes('res.cloudinary.com')) {
    return src
  }

  // Check if it's already a Cloudinary URL with transformations
  // Transformation parameters start with letters like w_, h_, c_, l_, q_, etc.
  // Version numbers start with 'v' followed by digits
  // We need to distinguish between: /image/upload/v123/ (no transformations) vs /image/upload/w_800/ (has transformations)
  const hasTransformations = src.includes('/image/upload/') && 
    (src.includes('/l_') || // Composite image with overlay
     src.match(/\/image\/upload\/(w_|h_|c_|q_|f_|fl_|a_|b_|d_|e_|g_|o_|p_|r_|s_|t_|u_|x_|y_|z_)/)) // Has transformation parameters
  
  if (hasTransformations) {
    // For existing product images that already have transformations, return as-is
    // Do not modify existing composite images - they are already stored in the database
    return src
  }

  // For existing product images (Cloudinary URL without transformations), return as-is
  // This ensures existing images continue to work without modification
  // Only new composite images generated by the API will have resolution limits applied
  return src
}
