-- Add design_png column to products table
-- This column will store the URL of the design-only PNG image generated by AI

ALTER TABLE products 
ADD COLUMN design_png TEXT;

-- Add comment to explain the column purpose
COMMENT ON COLUMN products.design_png IS 'URL of the design-only PNG image generated by AI (transparent background)';

-- Create index for better query performance if needed
CREATE INDEX IF NOT EXISTS idx_products_design_png ON products(design_png) WHERE design_png IS NOT NULL;
