-- Update design_png column to support multiple design PNGs (one per color)
-- This migration changes the design_png column from TEXT to TEXT[] to store multiple design URLs

-- First, create a backup of existing data if any
CREATE TABLE IF NOT EXISTS products_backup_design_png AS 
SELECT id, design_png FROM products WHERE design_png IS NOT NULL;

-- Drop the existing index
DROP INDEX IF EXISTS idx_products_design_png;

-- Alter the column to TEXT[] (array of text)
ALTER TABLE products 
ALTER COLUMN design_png TYPE TEXT[] USING 
  CASE 
    WHEN design_png IS NULL THEN NULL
    ELSE ARRAY[design_png]
  END;

-- Add comment to explain the updated column purpose
COMMENT ON COLUMN products.design_png IS 'Array of design-only PNG image URLs generated by AI (one per color, transparent background)';

-- Create new index for array column
CREATE INDEX IF NOT EXISTS idx_products_design_png_array ON products USING GIN(design_png) WHERE design_png IS NOT NULL;

-- Optional: Create a function to get design PNGs by color index
CREATE OR REPLACE FUNCTION get_design_png_by_color(product_id UUID, color_index INTEGER)
RETURNS TEXT AS $$
BEGIN
  RETURN (
    SELECT design_png[color_index + 1] 
    FROM products 
    WHERE id = product_id
  );
END;
$$ LANGUAGE plpgsql;

-- Optional: Create a function to add a design PNG to the array
CREATE OR REPLACE FUNCTION add_design_png(product_id UUID, new_design_png TEXT)
RETURNS TEXT[] AS $$
DECLARE
  current_designs TEXT[];
BEGIN
  SELECT design_png INTO current_designs FROM products WHERE id = product_id;
  
  IF current_designs IS NULL THEN
    current_designs := ARRAY[new_design_png];
  ELSE
    current_designs := current_designs || new_design_png;
  END IF;
  
  UPDATE products SET design_png = current_designs WHERE id = product_id;
  RETURN current_designs;
END;
$$ LANGUAGE plpgsql;
