import { NextRequest, NextResponse } from 'next/server'
import { getPrintfulClient, calculateDesignPosition } from '@/lib/printful'

export async function POST(_req: NextRequest) {
  try {
    const client = getPrintfulClient()
    
    console.log('Creating product with mockup image...')
    
    // Design information
    const designUrl = 'https://res.cloudinary.com/dmoyeva1q/image/upload/v1759828276/Rebel%20Mark%20Graphic%20Tee-design.png'
    const designPosition = calculateDesignPosition(1000, 1000, 'unisex')
    
    console.log('Design position:', designPosition)
    
    // Create mockup image URL (this would be generated by Printful's mockup API)
    // For now, we'll use a placeholder that represents the positioned design
    const mockupImageUrl = `https://via.placeholder.com/800x800/ffffff/000000?text=Mockup+with+Design+at+(${designPosition.left},${designPosition.top})`
    
    console.log('Mockup image URL:', mockupImageUrl)
    
    // Create product with mockup image
    const productData = {
      sync_product: {
        name: 'Rebel Mark Graphic Tee - Mockup',
        thumbnail: mockupImageUrl,
        description: 'Custom T-shirt with Rebel Mark design positioned on front'
      },
      sync_variants: [
        {
          variant_id: 1, // Using working variant ID
          retail_price: '29.99',
          files: [
            {
              type: 'default',
              url: designUrl,
              position: designPosition
            }
          ]
        }
      ]
    }
    
    console.log('Product data:', JSON.stringify(productData, null, 2))
    
    try {
      console.log('Creating product with mockup...')
      const createdProduct = await client.createProduct(productData)
      
      console.log('✅ Product with mockup created successfully!')
      console.log('Product ID:', createdProduct.id)
      
      return NextResponse.json({
        success: true,
        message: 'Product with mockup created successfully!',
        product: createdProduct,
        designInfo: {
          originalDesign: designUrl,
          mockupImage: mockupImageUrl,
          position: designPosition,
          dimensions: '1000x1000 pixels'
        },
        mockupDetails: {
          position: `(${designPosition.left}, ${designPosition.top})`,
          size: `${designPosition.width}x${designPosition.height}`,
          area: `${designPosition.area_width}x${designPosition.area_height}`,
          centered: designPosition.left === (designPosition.area_width - designPosition.width) / 2
        },
        nextSteps: [
          '1. Check Printful dashboard for the created product',
          '2. Verify the mockup image shows correct positioning',
          '3. Test the product in mockup generator',
          '4. Adjust position if needed'
        ],
        dashboardLinks: {
          printfulDashboard: 'https://www.printful.com/dashboard/default/products',
          mockupGenerator: 'https://www.printful.com/mockup-generator'
        }
      })
      
    } catch (error) {
      console.error('Product creation error:', error)
      return NextResponse.json({
        success: false,
        error: 'Failed to create product with mockup',
        details: error instanceof Error ? error.message : 'Unknown error',
        fallback: {
          designUrl,
          mockupImageUrl,
          position: designPosition,
          note: 'Product creation failed, but mockup data is ready'
        }
      }, { status: 500 })
    }
    
  } catch (error) {
    console.error('Mockup product creation error:', error)
    return NextResponse.json({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
      details: error
    }, { status: 500 })
  }
}
